# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    #default_filter_set_settings:
        #format: webp
    filter_sets:
        cache : ~
        post_image:
            quality: 75
            filters:
                #relative_resize:
                    #heighten: 400
                fixed:
                    width: 512
                    height: 384

        avatar_128:
            quality: 75
            filters:
                thumbnail  : { size : [128, 128], mode : outbound }
        avatar_64:
            quality: 75
            filters:
                thumbnail: { size: [64, 64], mode: outbound }
        avatar_32:
            quality: 75
            filters:
                thumbnail: { size: [32, 32], mode: outbound }
