# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    default_filter_set_settings:
        format: webp
    filter_sets:
        post_image:
            quality: 75
            filters:
                relative_resize:
                    heighten: 400
