twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
    strict_variables: true
    auto_reload: true
    globals:
        app_name: '%app_name%'
    date:
        format: d-m-Y

when@test:
    twig:
        strict_variables: true
