vich_uploader:
    db_driver: orm

    mappings:
        user_avatar:
            uri_prefix: /images/avatars
            upload_destination: '%kernel.project_dir%/public/images/avatars'
            namer:
                service: Vich\UploaderBundle\Naming\PropertyNamer
                options: { property: 'username' }

        post_image:
            uri_prefix: /images/posts
            upload_destination: '%kernel.project_dir%/public/images/posts'
            namer:
                service: Vich\UploaderBundle\Naming\UniqidNamer
            delete_on_update: true
            delete_on_remove: true
